version: '2'
services:
    nginx:
        image: "baiyuetribe/ysfaka:nginx"
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - php
    php:
        image: "baiyuetribe/ysfaka:php"
        networks:
            - frontend
            - backend
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            TZ: 'Asia/Shanghai'
            MYSQL_ROOT_PASSWORD: Passw0rd
        command: ['mysqld', '--character-set-server=utf8']
        networks:
            - backend
volumes:
    mysql-data:

networks:
    frontend:
    backend:
